repos:
-   repo: local
    # hooks:
    #   - id: pytest
    #     name: pytest
    #     language: system
    #     entry: pytest -v
    #     always_run: true
    #     pass_filenames: false
    #     stages: [commit]
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'venv/Scripts/pip freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]