# Generated by Django 4.1.3 on 2022-12-06 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compartilhamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabo',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='cabo',
            field=models.ManyToManyField(blank=True, null=True, to='compartilhamento.cabo'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='equipamento',
            field=models.ManyToManyField(blank=True, null=True, to='compartilhamento.equipamento'),
        ),
        migrations.RemoveField(
            model_name='ponto',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='ponto',
            name='nome',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='ocupacao',
            field=models.ManyToManyField(blank=True, null=True, to='compartilhamento.empresa'),
        ),
        migrations.AlterField(
            model_name='rede',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('descricao', models.TextField()),
                ('file', models.ImageField(upload_to='uploads/poste/%Y/%m/%d')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('updated_data', models.DateTimeField(auto_now=True)),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compartilhamento.tipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ponto',
            name='imagem',
            field=models.ManyToManyField(blank=True, null=True, to='compartilhamento.imagem'),
        ),
    ]
