# Generated by Django 4.1.3 on 2022-12-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compartilhamento', '0002_alter_cabo_descricao_alter_ponto_cabo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='cabo',
            field=models.ManyToManyField(blank=True, to='compartilhamento.cabo'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='equipamento',
            field=models.ManyToManyField(blank=True, to='compartilhamento.equipamento'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='imagem',
            field=models.ManyToManyField(blank=True, to='compartilhamento.imagem'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='ocupacao',
            field=models.ManyToManyField(blank=True, to='compartilhamento.empresa'),
        ),
    ]
