# Generated by Django 4.1.3 on 2022-12-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compartilhamento', '0003_alter_ponto_cabo_alter_ponto_equipamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='nome',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
