# Generated by Django 4.1.3 on 2022-12-07 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compartilhamento', '0004_alter_ponto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_tipo', to='compartilhamento.tipo'),
        ),
    ]
